package com.asghar.downloader.utils

import android.content.Context
import android.webkit.CookieManager
import java.io.File

/**
 * Exports the YouTube cookies that the user logged in with in this app's WebView
 * into a Netscape-format cookies.txt file that yt-dlp understands.
 *
 * YouTube's anti-bot challenge is solved for that user once the exported file
 * contains a valid `VISITOR_INFO1_LIVE` and a `__Secure-1PSID` (or older `SID`)
 * cookie. The user only has to do this once and the file is reused for every
 * later download.
 */
object CookieStore {
    private const val COOKIE_FILE_NAME = "youtube_cookies.txt"
    private const val MIN_COOKIE_SIZE = 64

    fun cookiesFile(context: Context): File =
        File(context.filesDir, COOKIE_FILE_NAME)

    fun hasCookies(context: Context): Boolean {
        val f = cookiesFile(context)
        return f.exists() && f.length() > MIN_COOKIE_SIZE
    }

    fun delete(context: Context): Boolean =
        runCatching { cookiesFile(context).delete() }.getOrDefault(false)

    /**
     * Refresh the on-disk cookie file from the system WebView cookie jar.
     * Must be called after the user has visited YouTube and signed in inside
     * the in-app login WebView (see [com.asghar.downloader.YouTubeLoginActivity]).
     */
    fun exportFromWebView(context: Context): Boolean {
        val manager = CookieManager.getInstance()
        if (!manager.acceptCookie()) manager.setAcceptCookie(true)
        manager.flush()
        val cookies = manager.getCookie("https://www.youtube.com/").orEmpty()
        if (cookies.isBlank()) return false
        val required = listOf("VISITOR_INFO1_LIVE", "SID", "__Secure-1PSID", "__Secure-3PSID")
        val hasAny = required.any { cookies.contains(it) }
        if (!hasAny) return false
        val file = cookiesFile(context)
        file.parentFile?.mkdirs()
        val netscape = buildString {
            append("# Netscape HTTP Cookie File\n")
            append("# Generated by AsgharDownloader for yt-dlp. Do not edit.\n\n")
            cookies.split(';').forEach { raw ->
                val trimmed = raw.trim()
                if (trimmed.isEmpty()) return@forEach
                val parts = trimmed.split('=', limit = 2)
                if (parts.size < 2) return@forEach
                val name = parts[0].trim()
                val value = parts[1].trim()
                if (name.isEmpty()) return@forEach
                val domain = if (name.startsWith("__Secure-") || name.startsWith("__Host-")) ".youtube.com" else ".youtube.com"
                val includeSubdomains = "TRUE"
                val secure = if (name.startsWith("__Secure-") || name.startsWith("__Host-") || name == "SID") "TRUE" else "FALSE"
                // Expire far in the future; yt-dlp ignores this but the format requires it.
                val expiry = "9999999999"
                append(domain).append('\t')
                append("TRUE").append('\t')              // Netscape uses TRUE/FALSE
                append("/").append('\t')
                append(secure).append('\t')
                append(expiry).append('\t')
                append(name).append('\t')
                append(value).append('\n')
                // Suppress unused-param warning while keeping the original
                // boolean expression around for clarity / future tweaks.
                if (includeSubdomains.isEmpty()) append("")
            }
        }
        return runCatching { file.writeText(netscape); true }.getOrDefault(false)
    }
}
